routes/web.php
<?php

use App\Jobs\SendEmailCompanies;
use App\Models\CompaniesModel;
use Illuminate\Support\Facades\Auth;
use App\Mail\NotificationCreateCompany;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Mail;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return redirect('en/login' );
});

Route::get('switchLanguage/{lang}', 'LocalizationController@switch')->name('lang.switch');

Route::group([
        'prefix' => '{locale}',
        'where' => ['locale' => '[a-zA-Z]{2}'],
        'middleware' => ['checkLangDB']
    ], function() {

    Auth::routes(['register' => false, 'reset' => false,]);
});

// if auth
Route::group([
        'prefix' => '{locale}', 
        'where' => ['locale' => '[a-zA-Z]{2}'],
        'middleware' => ['auth', 'checkjwt', 'checkLangDB']
    ], 
    function() {
        Route::resource('/companies', 'CompaniesController');
        Route::resource('/employees', 'EmployeesController');
        Route::resource('/items', 'ItemsController');
        Route::resource('/sells', 'SellsController');

        Route::get('/show-all', 'DataController@index')->name('data.index');
        Route::get('/sell-summary', 'DataController@sellSummary')->name('data.sellSummary');
        
        // filter Data
        Route::get('/searching-company', 'DataController@searchingCompany')->name('data.searchingCompany');
        Route::get('/searching-employee', 'DataController@searchingEmployee')->name('data.searchingEmployee');
        Route::post('/searching-sell-summary', 'DataController@searchingSellSummary')->name('data.searchingSellSummary');
        Route::get('/details-sell-summary/{id}', 'DataController@detailSellSummary')->name('data.detailSellSummary');

        /**
         * ajax post
        */
        Route::post('/get-price', 'DataController@getPrice')->name('data.getPrice');

        // import Data
        Route::post('/import-data-companies', 'CompaniesController@importCompanies')->name('import.companies');
        Route::post('/import-data-employee', 'EmployeesController@importEmployee')->name('import.employee');

});

resources/views/partials/alert.blade.php
{{-- Alert --}}

    @if (session('error'))
        <div class="alert bg-pink alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{ session('error') }}
        </div>
    @endif

    @if (session('success'))
        <div class="alert bg-green alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{ session('success') }}
            
        </div>
    @endif

    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{$error}}
            </div>
        @endforeach
    @endif

resources/views/partials/favicon.blade.php
<link rel="icon" href="{{ asset('img/favicon/favicon-LN.ico')}}" type="image/x-icon">

resources/views/partials/modals.blade.php
 <!-- Default Size Companies-->
 <div class="modal fade" id="defaultModalCompanies" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="defaultModalLabel">
                    {{ __('companiesMenu.LabelImportCompany') }}
                </h4>
            </div>
            <div class="modal-body">
                <form action="{{ route('import.companies', app()->getLocale() )}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <label for="data_company">{{ __('companiesMenu.LabelImportCompany') }}</label>
                    <div class="form-group">
                        <div class="form-line">
                            <input type="file" name="data_company" id="data_company" class="form-control" required>
                        </div>
                    </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-link waves-effect">{{ __('labelAction.saveButtonAction') }}</button>
                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">{{ __('labelAction.closeButtonAction') }}</button>
            </div>
            </form>
        </div>
    </div>
</div>

 <!-- Default Size Companies-->
 <div class="modal fade" id="defaultModalEmployee" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="defaultModalLabel">
                    {{ __('employeesMenu.LabelImportEmployee') }}
                </h4>
            </div>
            <div class="modal-body">
                <form action="{{ route('import.employee', app()->getLocale() )}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <label for="data_employee">{{ __('employeesMenu.LabelImportEmployee') }}</label>
                    <div class="form-group">
                        <div class="form-line">
                            <input type="file" name="data_employee" id="data_employee" class="form-control" required>
                        </div>
                    </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-link waves-effect">{{ __('labelAction.saveButtonAction') }}</button>
                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">{{ __('labelAction.closeButtonAction') }}</button>
            </div>
            </form>
        </div>
    </div>
</div>

resources/views/partials/sideBar.blade.php
<!-- #Top Bar -->
<section>
    <!-- Left Sidebar -->
    <aside id="leftsidebar" class="sidebar">
        <!-- User Info -->
        <div class="user-info">
            <div class="image">
                <img src="{{ asset('adminSB/images/user.png') }}" width="48" height="48" alt="User" />
            </div>
            <div class="info-container">
                {{-- <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ __('sideBarPanel.headerName') }}: {{ ucwords(Auth::user()->email) }}</div> --}}
                <div class="email">{{ __('sideBarPanel.headerEmail') }}: 
                    {{ Session::get('jwt_data')->email }}
                </div>
                <div class="btn-group user-helper-dropdown">
                    <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a class="dropdown-item" href="{{ route('logout', app()->getLocale() ) }}"
                                onclick="event.preventDefault();
                                            document.getElementById('logout-form').submit();">
                                    <i class="material-icons">input</i>
                                    {{ __('sideBarPanel.headerLogOut') }}
                            </a>
                            <form id="logout-form" action="{{ route('logout', app()->getLocale() ) }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- #User Info -->
        <!-- Menu -->
        <div class="menu">
            <ul class="list">
                <li class="header">{{ __('sideBarPanel.titleHeaderNavigation')}}</li>       
                <li class="<?= isset($filter_data_menu) ? 'active' : ''; ?>">
                    <a href="{{ route('data.index', app()->getLocale()) }}">
                        <i class="material-icons">library_books</i>
                        <span>{{ __('sideBarPanel.titleFilterData')}}</span>
                    </a>
                </li>         
                <li class="<?= isset($companies) ? 'active' : ''; ?>">
                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">account_balance</i>
                        <span>{{ __('sideBarPanel.titleFirstMenu')}}</span>
                    </a>
                    <ul class="ml-menu ">
                        <li class= <?= isset($indexCompanies) ? 'active' : ''; ?>>
                            <a href="{{ route('companies.index', app()->getLocale() ) }}">{{ __('sideBarPanel.subOneTitleFirstMenu')}} </a>
                        </li>
                        <li class= <?= isset($crateCompanies) ? 'active' : ''; ?>>
                            <a href="{{ route('companies.create', app()->getLocale() ) }}">{{ __('sideBarPanel.subTwoTitleFirstMenu')}}</a>
                        </li>
                    </ul>
                </li>

                <li class="<?= isset($employees_menu) ? 'active' : ''; ?>">
                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">person_add</i>
                        <span>{{ __('sideBarPanel.titleSecondMenu')}}</span>
                    </a>
                    <ul class="ml-menu ">
                        <li class= <?= isset($indexEmployees) ? 'active' : ''; ?>>
                            <a href="{{ route('employees.index', app()->getLocale() ) }}">{{ __('sideBarPanel.subOneTitleSecondMenu')}} </a>
                        </li>
                        <li class= <?= isset($crateEmployees) ? 'active' : ''; ?>>
                            <a href="{{ route('employees.create', app()->getLocale() ) }}">{{ __('sideBarPanel.subTwoTitleSecondMenu')}}</a>
                        </li>
                    </ul>
                </li>

                <li class="<?= isset($items_menu) ? 'active' : ''; ?>">
                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">class</i>
                        <span>{{ __('sideBarPanel.titleThirdMenu')}}</span>
                    </a>
                    <ul class="ml-menu ">
                        <li class= <?= isset($index_menu) ? 'active' : ''; ?>>
                            <a href="{{ route('items.index', app()->getLocale() ) }}">{{ __('sideBarPanel.subOneTitleThirdMenu')}} </a>
                        </li>
                        <li class= <?= isset($create_menu) ? 'active' : ''; ?>>
                            <a href="{{ route('items.create', app()->getLocale() ) }}">{{ __('sideBarPanel.subTwoTitleThirdMenu')}}</a>
                        </li>
                    </ul>
                </li>

                <li class="<?= isset($sells_menu) ? 'active' : ''; ?>">
                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">shopping_cart</i>
                        <span>{{ __('sideBarPanel.titleFourthMenu')}}</span>
                    </a>
                    <ul class="ml-menu ">
                        <li class= <?= isset($index_sells) ? 'active' : ''; ?>>
                            <a href="{{ route('sells.index', app()->getLocale() ) }}">{{ __('sideBarPanel.subOneTitleFourthMenu')}} </a>
                        </li>
                        <li class= <?= isset($create_sells) ? 'active' : ''; ?>>
                            <a href="{{ route('sells.create', app()->getLocale() ) }}">{{ __('sideBarPanel.subTwoTitleFourthMenu')}}</a>
                        </li>
                        <li class= <?= isset($sells_summary_daily) ? 'active' : ''; ?>>
                            <a href="{{ route('data.sellSummary', app()->getLocale() ) }}">{{ __('sideBarPanel.subThreeTitleFourthMenu')}}</a>
                        </li>
                    </ul>
                </li>
                                    
            </ul>
        </div>
        <!-- #Menu -->
        <!-- Footer -->
        <div class="legal">
            <div class="copyright">
                &copy; 2021 <a href="javascript:void(0);">Mini CRM</a>.
            </div>
            <div class="version">
                <b>{{ __('sideBarPanel.version') }}: </b> 0.0.1
            </div>
            <div class="">
                <div class="row clearfix">
                    @foreach (Session::get('lang_data') as $item)
                        <div class="col-xs-1 col-md-1 col-lg-1">
                            <a href="{{ route('lang.switch', [$item->lang]) }}" alt="English">
                                <span class="flag-icon {{ $item->icon }}"></span>
                            </a>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
        <!-- #Footer -->
    </aside>
    <!-- #END# Left Sidebar -->
    <!-- Right Sidebar -->
    <aside id="rightsidebar" class="right-sidebar">
        <ul class="nav nav-tabs tab-nav-right" role="tablist">
            <li role="presentation" class="active"><a href="#skins" data-toggle="tab">SKINS</a></li>
            <li role="presentation"><a href="#settings" data-toggle="tab">SETTINGS</a></li>
        </ul>
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade in active in active" id="skins">
                <ul class="demo-choose-skin">
                    <li data-theme="red" class="active">
                        <div class="red"></div>
                        <span>Red</span>
                    </li>
                    <li data-theme="pink">
                        <div class="pink"></div>
                        <span>Pink</span>
                    </li>
                    <li data-theme="purple">
                        <div class="purple"></div>
                        <span>Purple</span>
                    </li>
                    <li data-theme="deep-purple">
                        <div class="deep-purple"></div>
                        <span>Deep Purple</span>
                    </li>
                    <li data-theme="indigo">
                        <div class="indigo"></div>
                        <span>Indigo</span>
                    </li>
                    <li data-theme="blue">
                        <div class="blue"></div>
                        <span>Blue</span>
                    </li>
                    <li data-theme="light-blue">
                        <div class="light-blue"></div>
                        <span>Light Blue</span>
                    </li>
                    <li data-theme="cyan">
                        <div class="cyan"></div>
                        <span>Cyan</span>
                    </li>
                    <li data-theme="teal">
                        <div class="teal"></div>
                        <span>Teal</span>
                    </li>
                    <li data-theme="green">
                        <div class="green"></div>
                        <span>Green</span>
                    </li>
                    <li data-theme="light-green">
                        <div class="light-green"></div>
                        <span>Light Green</span>
                    </li>
                    <li data-theme="lime">
                        <div class="lime"></div>
                        <span>Lime</span>
                    </li>
                    <li data-theme="yellow">
                        <div class="yellow"></div>
                        <span>Yellow</span>
                    </li>
                    <li data-theme="amber">
                        <div class="amber"></div>
                        <span>Amber</span>
                    </li>
                    <li data-theme="orange">
                        <div class="orange"></div>
                        <span>Orange</span>
                    </li>
                    <li data-theme="deep-orange">
                        <div class="deep-orange"></div>
                        <span>Deep Orange</span>
                    </li>
                    <li data-theme="brown">
                        <div class="brown"></div>
                        <span>Brown</span>
                    </li>
                    <li data-theme="grey">
                        <div class="grey"></div>
                        <span>Grey</span>
                    </li>
                    <li data-theme="blue-grey">
                        <div class="blue-grey"></div>
                        <span>Blue Grey</span>
                    </li>
                    <li data-theme="black">
                        <div class="black"></div>
                        <span>Black</span>
                    </li>
                </ul>
            </div>
            <div role="tabpanel" class="tab-pane fade" id="settings">
                <div class="demo-settings">
                    <p>GENERAL SETTINGS</p>
                    <ul class="setting-list">
                        <li>
                            <span>Report Panel Usage</span>
                            <div class="switch">
                                <label><input type="checkbox" checked><span class="lever"></span></label>
                            </div>
                        </li>
                        <li>
                            <span>Email Redirect</span>
                            <div class="switch">
                                <label><input type="checkbox"><span class="lever"></span></label>
                            </div>
                        </li>
                    </ul>
                    <p>SYSTEM SETTINGS</p>
                    <ul class="setting-list">
                        <li>
                            <span>Notifications</span>
                            <div class="switch">
                                <label><input type="checkbox" checked><span class="lever"></span></label>
                            </div>
                        </li>
                        <li>
                            <span>Auto Updates</span>
                            <div class="switch">
                                <label><input type="checkbox" checked><span class="lever"></span></label>
                            </div>
                        </li>
                    </ul>
                    <p>ACCOUNT SETTINGS</p>
                    <ul class="setting-list">
                        <li>
                            <span>Offline</span>
                            <div class="switch">
                                <label><input type="checkbox"><span class="lever"></span></label>
                            </div>
                        </li>
                        <li>
                            <span>Location Permission</span>
                            <div class="switch">
                                <label><input type="checkbox" checked><span class="lever"></span></label>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </aside>
    <!-- #END# Right Sidebar -->
</section>

resources/views/partials/topBar.blade.php
 <!-- Page Loader -->
 <div class="page-loader-wrapper">
    <div class="loader">
        <div class="preloader">
            <div class="spinner-layer pl-red">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
        <p>Please wait...</p>
    </div>
</div>
<!-- #END# Page Loader -->
<!-- Overlay For Sidebars -->
<div class="overlay"></div>
<!-- #END# Overlay For Sidebars -->
<!-- Search Bar -->
<div class="search-bar">
    <div class="search-icon">
        <i class="material-icons">search</i>
    </div>
    <input type="text" placeholder="START TYPING...">
    <div class="close-search">
        <i class="material-icons">close</i>
    </div>
</div>
<!-- #END# Search Bar -->
<!-- Top Bar -->
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            {{-- <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a> --}}
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="#">Mini CRM</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            {{-- Language --}}
            <ul class="nav navbar-nav navbar-right">

            </ul>
        </div>
    </div>
</nav>
<!-- #Top Bar --