routes/web.php
<?php

use App\Jobs\SendEmailCompanies;
use App\Models\CompaniesModel;
use Illuminate\Support\Facades\Auth;
use App\Mail\NotificationCreateCompany;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Mail;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return redirect('en/login' );
});

Route::get('switchLanguage/{lang}', 'LocalizationController@switch')->name('lang.switch');

Route::group([
        'prefix' => '{locale}',
        'where' => ['locale' => '[a-zA-Z]{2}'],
        'middleware' => ['checkLangDB']
    ], function() {

    Auth::routes(['register' => false, 'reset' => false,]);
});

// if auth
Route::group([
        'prefix' => '{locale}', 
        'where' => ['locale' => '[a-zA-Z]{2}'],
        'middleware' => ['auth', 'checkjwt', 'checkLangDB']
    ], 
    function() {
        Route::resource('/companies', 'CompaniesController');
        Route::resource('/employees', 'EmployeesController');
        Route::resource('/items', 'ItemsController');
        Route::resource('/sells', 'SellsController');

        Route::get('/show-all', 'DataController@index')->name('data.index');
        Route::get('/sell-summary', 'DataController@sellSummary')->name('data.sellSummary');
        
        // filter Data
        Route::get('/searching-company', 'DataController@searchingCompany')->name('data.searchingCompany');
        Route::get('/searching-employee', 'DataController@searchingEmployee')->name('data.searchingEmployee');
        Route::post('/searching-sell-summary', 'DataController@searchingSellSummary')->name('data.searchingSellSummary');
        Route::get('/details-sell-summary/{id}', 'DataController@detailSellSummary')->name('data.detailSellSummary');

        /**
         * ajax post
        */
        Route::post('/get-price', 'DataController@getPrice')->name('data.getPrice');

        // import Data
        Route::post('/import-data-companies', 'CompaniesController@importCompanies')->name('import.companies');
        Route::post('/import-data-employee', 'EmployeesController@importEmployee')->name('import.employee');

});

resources/views/admin-panel/show/companies-data.blade.php
@extends('layouts.adminPanel')

@section('title', __('companiesMenu.titleCompanyData') )

@section('custom-css')
    <!-- Bootstrap Core Css -->
    <link href="{{ asset ('adminSB/plugins/bootstrap/css/bootstrap.css')}}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{ asset ('adminSB/plugins/node-waves/waves.css')}}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{ asset ('adminSB/plugins/animate-css/animate.css')}}" rel="stylesheet" />

    <!-- JQuery DataTable Css -->
    <link href="{{ asset ('adminSB/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">

    <!-- Multi Select Css -->
    <link href="{{ asset ('adminSB/plugins/multi-select/css/multi-select.css')}}" rel="stylesheet">
   
    <!-- Bootstrap Select Css -->
    <link href="{{ asset ('adminSB/plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{{ asset ('adminSB/css/style.css')}}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="{{ asset ('adminSB/css/themes/all-themes.css')}}" rel="stylesheet" />
@endsection


@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2> {{ __('companiesMenu.titleCompanyData') }} </h2>
            </div>

            <!-- Basic Examples -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                {{ __('companiesMenu.titleCompanyData') }}
                            </h2>
                        </div>
                        <div class="body">
                            @include('partials.alert')

                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                    <thead>
                                        <tr>
                                            <th>{{ __('companiesMenu.tableNumber') }}</th>
                                            <th>{{ __('companiesMenu.tableidCompany') }}</th>
                                            <th>{{ __('companiesMenu.tableCompanyName') }}</th>
                                            <th>{{ __('companiesMenu.tableCompanyEmail') }}</th>
                                            <th>{{ __('companiesMenu.tableCompanyLogo') }}</th>
                                            <th>{{ __('companiesMenu.tableAction') }}</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>{{ __('companiesMenu.tableNumber') }}</th>
                                            <th>{{ __('companiesMenu.tableidCompany') }}</th>
                                            <th>{{ __('companiesMenu.tableCompanyName') }}</th>
                                            <th>{{ __('companiesMenu.tableCompanyEmail') }}</th>
                                            <th>{{ __('companiesMenu.tableCompanyLogo') }}</th>
                                            <th>{{ __('companiesMenu.tableAction') }}</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        
                                        @foreach ($company_data as $indexCompany => $itemCompany)                                            
                                            <tr>
                                                <td>{{ $indexCompany + 1}}</td>
                                                <td>{{ $itemCompany->id_company }} </td>
                                                <td>{{ $itemCompany->name }} </td>
                                                <td>{{ $itemCompany->email }} </td>
                                                <td>
                                                    <img src="{{ asset('storage/'.$itemCompany->logo)}}" alt="company logo" width="100" height="100">
                                                </td>
                                                <td>
                                                    <form action="{{ route('companies.destroy', [app()->getLocale(), $itemCompany->id_company]) }}" method="post">
                                                        @csrf
                                                        {{ method_field('DELETE') }}
                                                        <a href="{{ route('companies.edit',[ app()->getLocale(), $itemCompany->id_company]) }}" class=" btn btn-sm btn-primary">{{ __('labelAction.editButtonAction') }}</a>
                                                        <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm( '{{ __('labelAction.warningDeleteAction') }} ')">{{ __('labelAction.deleteButtonAction') }}</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach 
                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Basic Examples -->
        </div>
    </div>

        
</section>
    
@endsection

@section('custom-js')
    <!-- Jquery Core Js -->
    <script src="{{ asset ('adminSB/plugins/jquery/jquery.min.js')}}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{{ asset ('adminSB/plugins/bootstrap/js/bootstrap.js')}}"></script>

    <!-- Select Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/bootstrap-select/js/bootstrap-select.js')}}"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/jquery-slimscroll/jquery.slimscroll.js')}}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/node-waves/waves.js')}}"></script>

     <!-- Jquery DataTable Plugin Js -->
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>

    <!-- Custom Js -->
    <script src="{{ asset ('adminSB/js/admin.js')}}"></script>
    <script src="{{ asset ('adminSB/js/pages/tables/jquery-datatable.js')}}"></script>
    <script src="{{ asset ('adminSB/js/pages/forms/advanced-form-elements.js')}}"></script>

    <!-- Demo Js -->
    <script src="{{ asset ('adminSB/js/demo.js')}}"></script>
@endsection

resources/views/admin-panel/show/employee-data.blade.php
@extends('layouts.adminPanel')

@section('title', __('employeesMenu.titleEmployeeData'))

@section('custom-css')
    <!-- Bootstrap Core Css -->
    <link href="{{ asset ('adminSB/plugins/bootstrap/css/bootstrap.css')}}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{ asset ('adminSB/plugins/node-waves/waves.css')}}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{ asset ('adminSB/plugins/animate-css/animate.css')}}" rel="stylesheet" />

    <!-- JQuery DataTable Css -->
    <link href="{{ asset ('adminSB/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">

    <!-- Multi Select Css -->
    <link href="{{ asset ('adminSB/plugins/multi-select/css/multi-select.css')}}" rel="stylesheet">
   
    <!-- Bootstrap Select Css -->
    <link href="{{ asset ('adminSB/plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{{ asset ('adminSB/css/style.css')}}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="{{ asset ('adminSB/css/themes/all-themes.css')}}" rel="stylesheet" />
@endsection


@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>{{ __('employeesMenu.titleEmployeeData') }}</h2>
            </div>

            <!-- Basic Examples -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                {{ __('employeesMenu.titleEmployeeData') }}
                            </h2>
                        </div>
                        <div class="body">
                            @include('partials.alert')

                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                    <thead>
                                        <tr>
                                            <th>{{ __('employeesMenu.tableNumber') }}</th>
                                            <th>{{ __('employeesMenu.tableFirstName') }}</th>
                                            <th>{{ __('employeesMenu.tableLastName') }}</th>
                                            <th>{{ __('employeesMenu.tableEmail') }}</th>
                                            <th>{{ __('employeesMenu.tablePhone') }}</th>
                                            <th>{{ __('employeesMenu.tableCompanyName') }}</th>
                                            <th>{{ __('employeesMenu.tableAction') }}</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>{{ __('employeesMenu.tableNumber') }}</th>
                                            <th>{{ __('employeesMenu.tableFirstName') }}</th>
                                            <th>{{ __('employeesMenu.tableLastName') }}</th>
                                            <th>{{ __('employeesMenu.tableEmail') }}</th>
                                            <th>{{ __('employeesMenu.tablePhone') }}</th>
                                            <th>{{ __('employeesMenu.tableCompanyName') }}</th>
                                            <th>{{ __('employeesMenu.tableAction') }}</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        
                                        @foreach ($dataEmployeesWithCompany as $index => $itemEmployee)                                            
                                            <tr>
                                                <td>{{ $index + 1}}</td>
                                                <td>{{ $itemEmployee->first_name }} </td>
                                                <td>{{ $itemEmployee->last_name }} </td>
                                                <td>{{ $itemEmployee->email }} </td>
                                                <td>{{ $itemEmployee->phone }} </td>
                                                <td>{{ $itemEmployee->company->name }} </td>
                                                <td>
                                                    <form action="{{ route('employees.destroy', [app()->getLocale(), $itemEmployee->id_employee]) }}" method="post">
                                                        @csrf
                                                        {{ method_field('DELETE') }}
                                                        <a href="{{ route('employees.edit',[ app()->getLocale(), $itemEmployee->id_employee]) }}" class=" btn btn-sm btn-primary">{{ __('labelAction.editButtonAction') }}</a>
                                                        <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?'')">{{ __('labelAction.deleteButtonAction') }}</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach 
                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Basic Examples -->
        </div>
    </div>

        
</section>
    
@endsection

@section('custom-js')
    <!-- Jquery Core Js -->
    <script src="{{ asset ('adminSB/plugins/jquery/jquery.min.js')}}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{{ asset ('adminSB/plugins/bootstrap/js/bootstrap.js')}}"></script>

    <!-- Select Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/bootstrap-select/js/bootstrap-select.js')}}"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/jquery-slimscroll/jquery.slimscroll.js')}}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/node-waves/waves.js')}}"></script>

     <!-- Jquery DataTable Plugin Js -->
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>

    <!-- Custom Js -->
    <script src="{{ asset ('adminSB/js/admin.js')}}"></script>
    <script src="{{ asset ('adminSB/js/pages/tables/jquery-datatable.js')}}"></script>
    <script src="{{ asset ('adminSB/js/pages/forms/advanced-form-elements.js')}}"></script>

    <!-- Demo Js -->
    <script src="{{ asset ('adminSB/js/demo.js')}}"></script>
@endsection

resources/views/admin-panel/show/items-data.blade.php
@extends('layouts.adminPanel')

@section('title', __('itemsMenu.titleItemsMenu') )

@section('custom-css')
    <!-- Bootstrap Core Css -->
    <link href="{{ asset ('adminSB/plugins/bootstrap/css/bootstrap.css')}}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{ asset ('adminSB/plugins/node-waves/waves.css')}}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{ asset ('adminSB/plugins/animate-css/animate.css')}}" rel="stylesheet" />

    <!-- JQuery DataTable Css -->
    <link href="{{ asset ('adminSB/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">

    <!-- Multi Select Css -->
    <link href="{{ asset ('adminSB/plugins/multi-select/css/multi-select.css')}}" rel="stylesheet">
   
    <!-- Bootstrap Select Css -->
    <link href="{{ asset ('adminSB/plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{{ asset ('adminSB/css/style.css')}}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="{{ asset ('adminSB/css/themes/all-themes.css')}}" rel="stylesheet" />
@endsection


@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2> {{ __('itemsMenu.titleItemsMenu') }} </h2>
            </div>

            <!-- Basic Examples -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                {{ __('itemsMenu.titleItemsMenu') }}
                            </h2>
                        </div>
                        <div class="body">
                            @include('partials.alert')

                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                    <thead>
                                        <tr>
                                            <th>{{ __('itemsMenu.tableNumber') }}</th>
                                            <th>{{ __('itemsMenu.tableItemName') }}</th>
                                            <th>{{ __('itemsMenu.tableItemPrice') }}</th>
                                            <th>{{ __('itemsMenu.tableAction') }}</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>{{ __('itemsMenu.tableNumber') }}</th>
                                            <th>{{ __('itemsMenu.tableItemName') }}</th>
                                            <th>{{ __('itemsMenu.tableItemPrice') }}</th>
                                            <th>{{ __('itemsMenu.tableAction') }}</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        
                                        @foreach ($items as $indexItem => $value)                                            
                                            <tr>
                                                <td>{{ $indexItem + 1}}</td>
                                                <td>{{ $value->name }} </td>
                                                <td>{{ $value->price }} </td>
                                                <td>
                                                    <form action="{{ route('items.destroy', [app()->getLocale(), $value->id]) }}" method="post">
                                                        @csrf
                                                        {{ method_field('DELETE') }}
                                                        <a href="{{ route('items.edit',[ app()->getLocale(), $value->id]) }}" class=" btn btn-sm btn-primary">{{ __('labelAction.editButtonAction') }}</a>
                                                        <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm( '{{ __('labelAction.warningDeleteAction') }} ')">{{ __('labelAction.deleteButtonAction') }}</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach 
                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Basic Examples -->
        </div>
    </div>

        
</section>
    
@endsection

@section('custom-js')
    <!-- Jquery Core Js -->
    <script src="{{ asset ('adminSB/plugins/jquery/jquery.min.js')}}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{{ asset ('adminSB/plugins/bootstrap/js/bootstrap.js')}}"></script>

    <!-- Select Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/bootstrap-select/js/bootstrap-select.js')}}"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/jquery-slimscroll/jquery.slimscroll.js')}}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/node-waves/waves.js')}}"></script>

     <!-- Jquery DataTable Plugin Js -->
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>

    <!-- Custom Js -->
    <script src="{{ asset ('adminSB/js/admin.js')}}"></script>
    <script src="{{ asset ('adminSB/js/pages/tables/jquery-datatable.js')}}"></script>
    <script src="{{ asset ('adminSB/js/pages/forms/advanced-form-elements.js')}}"></script>

    <!-- Demo Js -->
    <script src="{{ asset ('adminSB/js/demo.js')}}"></script>
@endsection