routes/web.php
<?php

use App\Jobs\SendEmailCompanies;
use App\Models\CompaniesModel;
use Illuminate\Support\Facades\Auth;
use App\Mail\NotificationCreateCompany;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Mail;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return redirect('en/login' );
});

Route::get('switchLanguage/{lang}', 'LocalizationController@switch')->name('lang.switch');

Route::group([
        'prefix' => '{locale}',
        'where' => ['locale' => '[a-zA-Z]{2}'],
        'middleware' => ['checkLangDB']
    ], function() {

    Auth::routes(['register' => false, 'reset' => false,]);
});

// if auth
Route::group([
        'prefix' => '{locale}', 
        'where' => ['locale' => '[a-zA-Z]{2}'],
        'middleware' => ['auth', 'checkjwt', 'checkLangDB']
    ], 
    function() {
        Route::resource('/companies', 'CompaniesController');
        Route::resource('/employees', 'EmployeesController');
        Route::resource('/items', 'ItemsController');
        Route::resource('/sells', 'SellsController');

        Route::get('/show-all', 'DataController@index')->name('data.index');
        Route::get('/sell-summary', 'DataController@sellSummary')->name('data.sellSummary');
        
        // filter Data
        Route::get('/searching-company', 'DataController@searchingCompany')->name('data.searchingCompany');
        Route::get('/searching-employee', 'DataController@searchingEmployee')->name('data.searchingEmployee');
        Route::post('/searching-sell-summary', 'DataController@searchingSellSummary')->name('data.searchingSellSummary');
        Route::get('/details-sell-summary/{id}', 'DataController@detailSellSummary')->name('data.detailSellSummary');

        /**
         * ajax post
        */
        Route::post('/get-price', 'DataController@getPrice')->name('data.getPrice');

        // import Data
        Route::post('/import-data-companies', 'CompaniesController@importCompanies')->name('import.companies');
        Route::post('/import-data-employee', 'EmployeesController@importEmployee')->name('import.employee');

});

resources/views/admin-panel/input_data/create-employees.blade.php
@extends('layouts.adminPanel')

@section('title', __('employeesMenu.titleCreateEmployee') )

@section('custom-css')
    <!-- Bootstrap Core Css -->
    <link href="{{ asset ('adminSB/plugins/bootstrap/css/bootstrap.css')}}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{ asset ('adminSB/plugins/node-waves/waves.css')}}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{ asset ('adminSB/plugins/animate-css/animate.css')}}" rel="stylesheet" />

    <!-- JQuery DataTable Css -->
    <link href="{{ asset ('adminSB/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">

    <!-- Multi Select Css -->
    <link href="{{ asset ('adminSB/plugins/multi-select/css/multi-select.css')}}" rel="stylesheet">
   
    <!-- Bootstrap Select Css -->
    <link href="{{ asset ('adminSB/plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{{ asset ('adminSB/css/style.css')}}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="{{ asset ('adminSB/css/themes/all-themes.css')}}" rel="stylesheet" />
@endsection


@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>{{ __('employeesMenu.titleCreateEmployee') }}</h2>
            </div>

            <!-- Vertical Layout -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Form {{ __('employeesMenu.titleCreateEmployee') }}
                            </h2>
                            <p class="m-t-2">
                                <a href="#" data-toggle="modal" data-target="#defaultModalEmployee"> {{ __('employeesMenu.LabelImportEmployee') }} </a>
                            </p>
                            <p class="text-right">
                                <a href="{{ asset('format-excel/Format-Import-Data-Employee.xlsx') }}"> {{ __('employeesMenu.LabelDownloadFormatImportEmployee') }} </a>
                            </p>
                        </div>
                            @include('partials.modals')
                        <div class="body">
                            {{-- alert --}}
                            @include('partials.alert')

                            <form action="{{ route('employees.store', app()->getLocale() ) }}" method="POST" enctype="multipart/form-data">
                                @csrf

                                <label for="id_company">{{ __('employeesMenu.LabelCompany') }}</label>
                                <div class="form-group">
                                    <select class="form-control show-tick" name="id_company" data-live-search="true" required>
                                        <option value="" class="text-center ml-auto mr-auto">-- {{ __('employeesMenu.LabelSelectCompany') }} -- </option>
                                        @foreach ($data_companies as $itemCompany)
                                            <option class="text-center ml-auto mr-auto" value="{{ $itemCompany->id_company }}" > {{ $itemCompany->name }} </option>
                                        @endforeach
                                    </select>
                                </div>

                                <label for="first_name">{{ __('employeesMenu.LabelFirstName') }}</label>
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="first_name" id="first_name" class="form-control" placeholder="{{ __('employeesMenu.LabelFirstName') }}" required>
                                    </div>
                                </div>

                                <label for="last_name">{{ __('employeesMenu.LabelLastName') }}</label>
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="last_name" id="last_name" class="form-control" placeholder="{{ __('employeesMenu.LabelLastName') }}" required>
                                    </div>
                                </div>

                                <label for="email">{{ __('employeesMenu.LabelEmail') }} </label>
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="email" name="email" id="email" class="form-control" placeholder="{{ __('employeesMenu.LabelEmail') }}" required>
                                    </div>
                                </div>

                                <label for="phone">{{ __('employeesMenu.LabelPhone') }} </label>
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="phone" id="phone" maxlength="13" pattern="[\d]+" title="Please Insert Number Only" class="form-control" placeholder="{{ __('employeesMenu.LabelPhone') }}" required>
                                    </div>
                                </div>

                                <label for="password">{{ __('employeesMenu.LabelPassword') }} </label>
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="password" name="password" id="password" class="form-control" placeholder="{{ __('employeesMenu.LabelPassword') }}" required>
                                    </div>
                                </div>
                                
                                <button type="submit" class="btn btn-primary m-t-15 waves-effect">{{ __('labelAction.saveButtonAction') }}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Vertical Layout -->

        </div>
    </div>

        
</section>
    
@endsection

@section('custom-js')
    <!-- Jquery Core Js -->
    <script src="{{ asset ('adminSB/plugins/jquery/jquery.min.js')}}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{{ asset ('adminSB/plugins/bootstrap/js/bootstrap.js')}}"></script>

    <!-- Select Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/bootstrap-select/js/bootstrap-select.js')}}"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/jquery-slimscroll/jquery.slimscroll.js')}}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/node-waves/waves.js')}}"></script>

     <!-- Jquery DataTable Plugin Js -->
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>

    <!-- Custom Js -->
    <script src="{{ asset ('adminSB/js/admin.js')}}"></script>
    <script src="{{ asset ('adminSB/js/pages/tables/jquery-datatable.js')}}"></script>
    <script src="{{ asset ('adminSB/js/pages/forms/advanced-form-elements.js')}}"></script>

    <!-- Demo Js -->
    <script src="{{ asset ('adminSB/js/demo.js')}}"></script>
@endsection

resources/views/admin-panel/input_data/create-items.blade.php
@extends('layouts.adminPanel')

@section('title', __('itemsMenu.titleItemsMenu') )

@section('custom-css')
    <!-- Bootstrap Core Css -->
    <link href="{{ asset ('adminSB/plugins/bootstrap/css/bootstrap.css')}}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{ asset ('adminSB/plugins/node-waves/waves.css')}}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{ asset ('adminSB/plugins/animate-css/animate.css')}}" rel="stylesheet" />

    <!-- JQuery DataTable Css -->
    <link href="{{ asset ('adminSB/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">

    <!-- Multi Select Css -->
    <link href="{{ asset ('adminSB/plugins/multi-select/css/multi-select.css')}}" rel="stylesheet">
   
    <!-- Bootstrap Select Css -->
    <link href="{{ asset ('adminSB/plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{{ asset ('adminSB/css/style.css')}}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="{{ asset ('adminSB/css/themes/all-themes.css')}}" rel="stylesheet" />
@endsection


@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>{{ __('itemsMenu.titleItemsMenu') }}</h2>
            </div>

            <!-- Vertical Layout -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Form {{ __('itemsMenu.titleItemsMenu') }}
                            </h2>
                        </div>
                        @include('partials.modals')
                        <div class="body">
                            {{-- alert --}}
                            @include('partials.alert')

                            <form action="{{ route('items.store', app()->getLocale() ) }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <label for="name">{{ __('itemsMenu.LabelItemName') }}</label>
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="name" id="name" class="form-control" placeholder="{{ __('itemsMenu.LabelItemName') }}" required>
                                    </div>
                                </div>

                                <label for="price">{{ __('itemsMenu.LabelPrice') }}</label>
                                <div class="input-group">
                                    <div class="form-line demo-masked-input">
                                        <input type="text" class="form-control" name="price" pattern="[\d]+" title="Please Insert Number Only" placeholder="{{ __('itemsMenu.placeholderINDCurrency') }}">
                                    </div>
                                </div>

                              
                                <button type="submit" class="btn btn-primary m-t-15 waves-effect">{{ __('labelAction.saveButtonAction') }}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Vertical Layout -->

        </div>
    </div>

        
</section>
    
@endsection

@section('custom-js')
    <!-- Jquery Core Js -->
    <script src="{{ asset ('adminSB/plugins/jquery/jquery.min.js')}}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{{ asset ('adminSB/plugins/bootstrap/js/bootstrap.js')}}"></script>

    <!-- Select Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/bootstrap-select/js/bootstrap-select.js')}}"></script>
    
    <!-- Input Mask Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/jquery-inputmask/jquery.inputmask.bundle.js') }}"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/jquery-slimscroll/jquery.slimscroll.js')}}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/node-waves/waves.js')}}"></script>

    <!-- Custom Js -->
    <script src="{{ asset ('adminSB/js/admin.js')}}"></script>
    {{-- <script src="{{ asset ('adminSB/js/pages/forms/advanced-form-elements.js') }}"></script> --}}

    <!-- Demo Js -->
    <script src="{{ asset ('adminSB/js/demo.js')}}"></script>
@endsection

resources/views/admin-panel/input_data/create-sells.blade.php
@extends('layouts.adminPanel')

@section('title', __('sellsMenu.titleSellsMenu') )

@section('custom-css')
    <!-- Bootstrap Core Css -->
    <link href="{{ asset ('adminSB/plugins/bootstrap/css/bootstrap.css')}}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{ asset ('adminSB/plugins/node-waves/waves.css')}}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{ asset ('adminSB/plugins/animate-css/animate.css')}}" rel="stylesheet" />

    <!-- JQuery DataTable Css -->
    <link href="{{ asset ('adminSB/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">

    <!-- Multi Select Css -->
    <link href="{{ asset ('adminSB/plugins/multi-select/css/multi-select.css')}}" rel="stylesheet">
   
    <!-- Bootstrap Select Css -->
    <link href="{{ asset ('adminSB/plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{{ asset ('adminSB/css/style.css')}}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="{{ asset ('adminSB/css/themes/all-themes.css')}}" rel="stylesheet" />
@endsection


@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>{{ __('sellsMenu.titleSellsMenu') }}</h2>
            </div>

            <!-- Vertical Layout -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Form {{ __('sellsMenu.titleSellsMenu') }}
                            </h2>
                        </div>
                            @include('partials.modals')
                        <div class="body">
                            {{-- alert --}}
                            @include('partials.alert')

                            <form action="{{ route('sells.store', app()->getLocale() ) }}" method="POST" enctype="multipart/form-data">
                                @csrf

                                <label for="employee">{{ __('sellsMenu.LabelEmployeeName') }}</label>
                                <div class="form-group">
                                    <select class="form-control show-tick" name="id_employee" data-live-search="true" required>
                                        <option value="" class="text-center ml-auto mr-auto">-- {{ __('sellsMenu.placeholderSelectEmployee') }} -- </option>
                                        @foreach ($employees as $employee)
                                            <option class="text-center ml-auto mr-auto" value="{{ $employee->id_employee }}" > {{ $employee->first_name }} {{ $employee->last_name}}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <label for="item">{{ __('sellsMenu.LabelItem') }}</label>
                                <div class="form-group" id="item-form">
                                    <select class="form-control show-tick" name="item_id" id="item_id" data-live-search="true" required>
                                        <option value="" class="text-center ml-auto mr-auto">-- {{ __('sellsMenu.placeholderSelectItem') }} -- </option>
                                        @foreach ($items as $item)
                                            <option class="text-center ml-auto mr-auto" value="{{ $item->id }}" > {{ $item->name }}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <label for="price">{{ __('sellsMenu.LabelItemPrice') }}</label>
                                <div class="input-group">
                                    <div class="form-line demo-masked-input">
                                        <input type="text" class="form-control" name="price" id="price" pattern="[\d]+" title="Please Insert Number Only" placeholder="{{ __('sellsMenu.placeholderCurrency') }}" readonly required>
                                    </div>
                                </div>
                                
                                
                                <label for="discount">{{ __('sellsMenu.LabelItemDiscount') }}</label>
                                <div class="input-group">
                                    <div class="form-line demo-masked-input">
                                        <input type="text" class="form-control" name="discount" pattern="[\d]+" title="Please Insert Number Only" placeholder="{{ __('sellsMenu.placeholderDiscount') }}">
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-primary m-t-15 waves-effect">{{ __('labelAction.saveButtonAction') }}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Vertical Layout -->

        </div>
    </div>

        
</section>
    
@endsection

@section('custom-js')
    <!-- Jquery Core Js -->
    <script src="{{ asset ('adminSB/plugins/jquery/jquery.min.js')}}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{{ asset ('adminSB/plugins/bootstrap/js/bootstrap.js')}}"></script>

    <!-- Select Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/bootstrap-select/js/bootstrap-select.js')}}"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/jquery-slimscroll/jquery.slimscroll.js')}}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/node-waves/waves.js')}}"></script>

    <!-- Custom Js -->
    <script src="{{ asset ('adminSB/js/admin.js')}}"></script>

    <!-- Demo Js -->
    <script src="{{ asset ('adminSB/js/demo.js')}}"></script>
    <script>
        $(document).on('click', '#item-form', function(){
            // locale
            let language = '{{ config('app.locale') }}';

            let item_id  = document.getElementById('item_id').value;
            let _token   = $('meta[name="csrf-token"]').attr('content');
            let url      = "/" + language + "/get-price";

            $.ajax({
                method: "POST",
                url: url,
                data: {
                    _token: _token, 
                    item_id: item_id 
                }
            }).done(function(message) {
                $("#price").val(message.data.price);
            });
        });
        
    </script>
@endsection

resources/views/admin-panel/input_data/create_company.blade.php
@extends('layouts.adminPanel')

@section('title', __('companiesMenu.titleCreateCompany') )

@section('custom-css')
    <!-- Bootstrap Core Css -->
    <link href="{{ asset ('adminSB/plugins/bootstrap/css/bootstrap.css')}}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{ asset ('adminSB/plugins/node-waves/waves.css')}}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{ asset ('adminSB/plugins/animate-css/animate.css')}}" rel="stylesheet" />

    <!-- JQuery DataTable Css -->
    <link href="{{ asset ('adminSB/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">

    <!-- Multi Select Css -->
    <link href="{{ asset ('adminSB/plugins/multi-select/css/multi-select.css')}}" rel="stylesheet">
   
    <!-- Bootstrap Select Css -->
    <link href="{{ asset ('adminSB/plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{{ asset ('adminSB/css/style.css')}}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="{{ asset ('adminSB/css/themes/all-themes.css')}}" rel="stylesheet" />
@endsection


@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>{{ __('companiesMenu.titleCreateCompany') }}</h2>
            </div>

            <!-- Vertical Layout -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Form {{ __('companiesMenu.titleCreateCompany') }}
                            </h2>
                            <p class="m-t-2">
                                <a href="#" data-toggle="modal" data-target="#defaultModalCompanies"> {{ __('companiesMenu.LabelImportCompany') }} </a>
                            </p>
                            <p class="text-right">
                                <a href="{{ asset('format-excel/Format-Import-Data-Companies') }}"> {{ __('companiesMenu.LabelDownloadFormatImportCompany') }} </a>
                            </p>
                        </div>
                        @include('partials.modals')
                        <div class="body">
                            {{-- alert --}}
                            @include('partials.alert')

                            <form action="{{ route('companies.store', app()->getLocale() ) }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <label for="name">{{ __('companiesMenu.LabelCompanyName') }}</label>
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="name" id="name" class="form-control" placeholder="{{ __('companiesMenu.LabelCompanyName') }}" required>
                                    </div>
                                </div>

                                <label for="email">{{ __('companiesMenu.LabelEmailCompany') }}</label>
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="email" name="email" id="email" class="form-control" placeholder="{{ __('companiesMenu.LabelEmailCompany') }}" required>
                                    </div>
                                </div>

                                <label for="logo">{{ __('companiesMenu.LabelLogoCompany') }}</label>
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="file" name="logo" id="logo" class="form-control">
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary m-t-15 waves-effect">{{ __('labelAction.saveButtonAction') }}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Vertical Layout -->

        </div>
    </div>

        
</section>
    
@endsection

@section('custom-js')
    <!-- Jquery Core Js -->
    <script src="{{ asset ('adminSB/plugins/jquery/jquery.min.js')}}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{{ asset ('adminSB/plugins/bootstrap/js/bootstrap.js')}}"></script>

    <!-- Select Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/bootstrap-select/js/bootstrap-select.js')}}"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/jquery-slimscroll/jquery.slimscroll.js')}}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{{ asset ('adminSB/plugins/node-waves/waves.js')}}"></script>

     <!-- Jquery DataTable Plugin Js -->
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
     <script src="{{ asset ('adminSB/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>

    <!-- Custom Js -->
    <script src="{{ asset ('adminSB/js/admin.js')}}"></script>
    <script src="{{ asset ('adminSB/js/pages/tables/jquery-datatable.js')}}"></script>
    <script src="{{ asset ('adminSB/js/pages/forms/advanced-form-elements.js')}}"></script>

    <!-- Demo Js -->
    <script src="{{ asset ('adminSB/js/demo.js')}}"></script>
@endsection